### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by seunghyukcho** [gimme1dollar/Cross#11]
홈페이지 소유자의 정보를 보여주는 page. 일종의 이력서이다.

- 개인정보(전화번호, 이메일 등)
- 학력
- 프로젝트
- 논문

**Comment by gimme1dollar** [comment]
profile과 meme dictionary를 두 개의 section으로 나누지 말고, 한 뷰로 볼 수 있도록, 프로필 아래에 meme dictionary가 바로 뜨게 변경 요청.

**Comment by gimme1dollar** [comment]
학력, 프로젝트, 논문 등은 CV pdf 파일 바로 다운받는 링크를 걸어둬 다운로드할 수 있게 할 예정. profile box에는 사진과 몇 줄 짜리 설명만 있으면 충분 (20200921 상태에서 크게 변경할 내용 없음).

**Comment by seunghyukcho** [comment]
- [ ] 프로필과 Meme list 페이지 병합
- [ ] 프로필은 사진과 소개 몇 줄로 정리. 구체적인 CV는 pdf로 대체
