### ISSUE TITLE
Data Model 정의

### ISSUE THREAD

**Issue by seunghyukcho** [gimme1dollar/Cross#2]
- Meme
    - uid
    - name
    - type(Project / Cluster)
    - level
    - parent
    - state(On-going / Stopped / Planned)
- Detail
    - uid
    - category
    - summary
    - description
    - remark

**Comment by gimme1dollar** [comment]
draw.io 이용해서 개략적인 visualization 진행 중

Data model 다시 정리해보자면,
xlsx 파일 하나는 meme하나로 의미
(meme에 cluster와 project가 있음. spatial한 것과 temporal한 성질이 각각 부각됨)
meme들에는 content가 있음
content는 meme xlsx파일에서의 각 raw에 해당

meme {
name
type : project, cluster
progress {
phase
chapter
}
relationship {
parent
}
}



content {
category
concept
detail
remark
}
