### ISSUE TITLE
MemeList Page

### ISSUE THREAD

**Issue by gimme1dollar** [gimme1dollar/Cross#4]
Parse된 meme tree로 부터 meme 하나의 페이지로 이동하는 페이지

기본적으로, meme들 사이의 관계를 보여주는 그림이 삽입될 예정. (그림은 그리는 중)

1) tree에는 level에 따라서 높을 수록 맨 왼쪽에 붙어있고, 낮아질수록 점차 왼쪽에서부터의 빈 칸이 많아지는 형태. 즉, level 1의 meme 이름이 level 5의 meme 이름보다 더 오른쪽에 표시 됨. 

2) meme은 parent meme 아래에 표시됨. 같은 parent를 지니면 level이 낮을 수록 밑에 표시됨.

3) state에 따라서 meme의 이름 색 변경할 수 있도록. 

4) meme의 바로 아래에 phase별 내용이 뜨도록. (phase는 내용은 각 sheet의 맨 첫 raw 첫 column에 적어뒀음.) 이 부분은 한번 visulization을 보고 디테일하게 조정하게 될 것 같음.

5) meme 이름 클릭하면 detail들을 보여주는 페이지로 이동. meme 하나 당 하나의 페이지가 기본.

6) meme여러개를 체크해서 이름을 클릭하면, 해당 클릭된 meme들의 detail들이 concatenate돼서 페이지에 출력되도록. (이 부분은 phase 별 체크박스를 하게 될 수도 있음.)

**Comment by seunghyukcho** [comment]
vuetify에서 제공하는 treeview component를 사용할 예정.
- https://vuetifyjs.com/ko/components/treeview/
- level에 따른 분포는 같이하면 안 예쁠 것 같아, 일단 계층구조만 표시

**Comment by gimme1dollar** [comment]
profile page로 통합.
